/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#131315",
        "on-tertiary": "#5f003e",
        "secondary-fixed": "#e3c6ff",
        "inverse-on-surface": "#555557",
        "primary-fixed": "#c284ff",
        "on-error": "#490013",
        "surface": "#0e0e10",
        "tertiary-dim": "#f271b5",
        "surface-variant": "#262528",
        "on-error-container": "#ffb2b9",
        "primary-dim": "#9c48ea",
        "background": "#0e0e10",
        "error-container": "#a70138",
        "tertiary": "#ff86c3",
        "error-dim": "#d73357",
        "on-secondary": "#4c2e6d",
        "on-tertiary-fixed-variant": "#73004b",
        "secondary-dim": "#c8a5ed",
        "on-tertiary-fixed": "#360021",
        "tertiary-fixed": "#ff8bc5",
        "on-primary-fixed": "#000000",
        "on-background": "#f6f3f5",
        "surface-container-lowest": "#000000",
        "outline": "#767577",
        "secondary-container": "#573878",
        "error": "#ff6e84",
        "on-secondary-container": "#e2c5ff",
        "secondary": "#d6b2fc",
        "surface-container": "#19191c",
        "surface-bright": "#2c2c2f",
        "on-primary-container": "#360061",
        "on-primary": "#47007c",
        "on-tertiary-container": "#4a002f",
        "tertiary-container": "#f673b7",
        "on-primary-fixed-variant": "#430076",
        "tertiary-fixed-dim": "#f976ba",
        "surface-container-highest": "#262528",
        "on-secondary-fixed": "#432564",
        "inverse-surface": "#fcf8fb",
        "surface-container-high": "#1f1f22",
        "on-secondary-fixed-variant": "#614283",
        "secondary-fixed-dim": "#d9b5ff",
        "primary": "#cc97ff",
        "primary-fixed-dim": "#b971ff",
        "on-surface": "#f6f3f5",
        "surface-tint": "#cc97ff",
        "primary-container": "#c284ff",
        "surface-dim": "#0e0e10",
        "inverse-primary": "#842cd3",
        "on-surface-variant": "#acaaad",
        "outline-variant": "#48474a"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem", 
        "lg": "0.5rem", 
        "xl": "0.75rem", 
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
